"""
Radian YOLO26 Annotated Live Stream Server

The object-detector.cpp application owns the RTSP stream,
YOLO26 inference, nvdsosd annotation and JPEG encoding.

This server does NOT capture /dev/video0.

Instead it proxies the annotated MJPEG stream generated by
object-detector.cpp.

Flow:

    RTSP
      |
      v
    YOLO26
      |
      v
    nvdsosd
      |
      v
    Annotated JPEG
      |
      v
    object-detector :5002
      |
      v
    this server :5001
      |
      v
    /video_feed
      |
      v
    Dashboard
"""

import http.client
import time

from flask import Flask, Response

from logger import get_logger


logger = get_logger("live_stream_server")

app = Flask(__name__)


# ============================================================
# Configuration
# ============================================================

# C++ object-detector MJPEG server
OBJECT_DETECTOR_HOST = "127.0.0.1"
OBJECT_DETECTOR_PORT = 5002
OBJECT_DETECTOR_ENDPOINT = "/video_feed"


# Port exposed to the telemetry dashboard
LIVE_STREAM_PORT = 5001


# ============================================================
# Connect to object-detector
# ============================================================

def _connect_to_object_detector():
    """
    Connect to the annotated MJPEG stream generated by
    object-detector.cpp.

    Returns:
        HTTPConnection, HTTPResponse

    Raises:
        Exception if connection fails.
    """

    logger.info(
        "Connecting to YOLO26 annotated stream: "
        "http://%s:%d%s",
        OBJECT_DETECTOR_HOST,
        OBJECT_DETECTOR_PORT,
        OBJECT_DETECTOR_ENDPOINT,
    )

    connection = http.client.HTTPConnection(
        OBJECT_DETECTOR_HOST,
        OBJECT_DETECTOR_PORT,
        timeout=10,
    )

    connection.request(
        "GET",
        OBJECT_DETECTOR_ENDPOINT,
    )

    response = connection.getresponse()

    if response.status != 200:
        connection.close()

        raise RuntimeError(
            "Object-detector returned HTTP "
            f"{response.status}"
        )

    content_type = response.getheader(
        "Content-Type",
        "",
    )

    logger.info(
        "Connected to object-detector "
        "annotated stream"
    )

    logger.info(
        "Source Content-Type: %s",
        content_type,
    )

    return connection, response


# ============================================================
# MJPEG generator
# ============================================================

def _generate_mjpeg():
    """
    Read the already-annotated MJPEG stream from
    object-detector.cpp and forward it to the browser.

    No decoding.
    No YOLO inference.
    No OpenCV.
    No FFmpeg.
    No /dev/video0.

    The bounding boxes and labels are already present
    in the JPEG frames.
    """

    connection = None

    while True:

        try:

            connection, response = (
                _connect_to_object_detector()
            )

            while True:

                chunk = response.read(
                    16 * 1024
                )

                if not chunk:

                    logger.warning(
                        "YOLO26 annotated stream "
                        "closed."
                    )

                    break

                yield chunk

        except Exception as exc:

            logger.error(
                "Annotated live-stream error: %s",
                exc,
            )

            # Wait before reconnecting.
            time.sleep(2)

        finally:

            if connection is not None:

                try:
                    connection.close()

                except Exception:
                    pass

                connection = None


# ============================================================
# Dashboard video endpoint
# ============================================================

@app.route("/video_feed")
def video_feed():

    return Response(
        _generate_mjpeg(),

        mimetype=(
            "multipart/"
            "x-mixed-replace;"
            "boundary=frame"
        ),

        headers={
            "Cache-Control":
                "no-cache, "
                "no-store, "
                "must-revalidate",

            "Pragma":
                "no-cache",

            "Expires":
                "0",

            "Connection":
                "close",
        },
    )


# ============================================================
# Health endpoint
# ============================================================

@app.route("/health")
def health():

    return {
        "status": "ok",

        "source":
            "YOLO26 object-detector",

        "source_url":
            "http://127.0.0.1:5002/video_feed",

        "dashboard_endpoint":
            "/video_feed",
    }


# ============================================================
# Main
# ============================================================

if __name__ == "__main__":

    logger.info(
        "============================================================"
    )

    logger.info(
        "Radian YOLO26 Annotated Live Stream Server"
    )

    logger.info(
        "============================================================"
    )

    logger.info(
        "YOLO26 source:"
    )

    logger.info(
        "http://%s:%d%s",
        OBJECT_DETECTOR_HOST,
        OBJECT_DETECTOR_PORT,
        OBJECT_DETECTOR_ENDPOINT,
    )

    logger.info(
        "Dashboard endpoint:"
    )

    logger.info(
        "http://0.0.0.0:%d/video_feed",
        LIVE_STREAM_PORT,
    )

    logger.info(
        "============================================================"
    )

    app.run(
        host="0.0.0.0",
        port=LIVE_STREAM_PORT,
        threaded=True,
    )
